### ISSUE TITLE
Hide Share Button

### ISSUE THREAD

**Issue by arpitjain03** [karthikAdaptavant/AppImageViewer#1]
Is there any way to hide share button?

**Comment by haroldogtf** [comment]
I would also like to hide the sharing button

**Comment by arpitjain03** [comment]
Open ViewerToolbar

In func setupToolbar()

Comment these lines
        //btn.addTarget(browser, action: #selector(browser?.actionButtonPressed(_:)), for: .touchUpInside)
        //self.addSubview(btn)

**Comment by karthiikmk** [comment]
Closing this issue since it is not an issue
